name: thi_sat_hach
description: "Ứng dụng ôn thi sát hạch"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ✅ SQLite
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.19.0

  # ✅ UI & Animation
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  carousel_slider: ^4.2.1

  # ✅ Features
  image_picker: ^1.0.4
  clipboard: ^0.1.3
  password_strength: ^0.2.0  # Kept this one, updated to a more stable version
    # ✅ HTTP client (gọi API)
  http: ^1.2.2
    # ✅ Google Generative AI (Gemini)
  google_generative_ai: ^0.4.3
    # ✅ Đọc file .env (API key, config)
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # ✅ File database có sẵn
    - assets/Cau_Thi.db

    # ✅ Thư mục chứa tất cả ảnh câu hỏi và avatar
    - assets/img/
    - .env